blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import blog, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', blog, name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('newsletter.urls', namespace='newsletter')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.views import IndexView, contacts, ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, \
    ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    MailListView, MailDetailView, MailCreateView, MailUpdateView, MailDeleteView, toogle_activity

app_name = NewsletterConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', contacts, name='contacts'),

    path('client/', ClientListView.as_view(), name='client_list'),
    path('client/view/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/view/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
    path('message/create/', MessageCreateView.as_view(), name='create_message'),
    path('message/edit/<int:pk>/', MessageUpdateView.as_view(), name='edit_message'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('mail/', MailListView.as_view(), name='mail_list'),
    path('mail/view/<int:pk>/', MailDetailView.as_view(), name='view_mail'),
    path('mail/create/', MailCreateView.as_view(), name='create_mail'),
    path('mail/edit/<int:pk>/', MailUpdateView.as_view(), name='edit_mail'),
    path('mail/delete/<int:pk>/', MailDeleteView.as_view(), name='delete_mail'),
    path('mail/activity/<int:pk>/', toogle_activity, name='toogle_activity'),
]

newsletter/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.CharField(max_length=150, verbose_name='email', unique=True)
    last_name = models.CharField(max_length=150, verbose_name="фамилия")
    first_name = models.CharField(max_length=150, verbose_name='имя')
    father_name = models.CharField(max_length=150, verbose_name='отчество')
    comment = models.TextField(verbose_name='содержимое', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')

    def __str__(self):
        return f' {self.last_name} {self.first_name} {self.father_name} ({self.email})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    title = models.CharField(max_length=250, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Mail(models.Model):
    PERIOD_CHOICES = [
        ('раз в день', 'раз в день'),
        ('раз в неделю', 'раз в неделю'),
        ('раз в месяц', 'раз в месяц'),
    ]
    STATUS_CHOICES = [
        ('создана', 'создана'),
        ('завершена', 'завершена'),
        ('запущена', 'запущена'),
    ]
    name = models.CharField(max_length=100, verbose_name='Название рассылки', default='рассылка')
    clients = models.ManyToManyField(Client, verbose_name='кому (клиенты сервиса)')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="сообщение")
    date_start = models.DateField(verbose_name='дата начала рассылки', default=timezone.now)
    date_next = models.DateTimeField(verbose_name="следующая дата рассылки",default=timezone.now)
    date_end = models.DateField(verbose_name='дата окончания рассылки', default=timezone.now)
    start_time = models.TimeField(verbose_name='время рассылки', default=timezone.now)
    period = models.CharField(max_length=50, choices=PERIOD_CHOICES, verbose_name='периодичность рассылки',
                              default='раз в день')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name='статус рассылки',
                              default='создана')
    is_active = models.BooleanField(default=True, verbose_name='активация рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')

    def __str__(self):
        return f'{self.name}: Дата начала: {self.date_start}, Дата окончания: {self.date_end}. Статус: {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ("set_is_active", "Активация рассылки")
        ]


class Log(models.Model):
    mail = models.ForeignKey(Mail, on_delete=models.CASCADE, verbose_name='рассылка')
    last_time_mail = models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')
    status = models.CharField(max_length=50, verbose_name='статус попытки')
    response = models.TextField(verbose_name='ответ сервера', **NULLABLE)

    def __str__(self):
        return (f'Дата и время последней попытки: {self.last_time_mail}.'
                f' Статус попытки:{self.status}')

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

newsletter/forms.py
from django import forms
from django.forms import DateTimeInput

from newsletter.models import Client, Mail, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('owner',)


class MailForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(owner=user)
        self.fields['message'].queryset = Message.objects.filter(owner=user)

    class Meta:
        model = Mail
        exclude = ('is_active', 'owner')

        widgets = {
            'start_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'placeholder': 'ДД.ММ.ГГГГ ЧЧ:ММ:СС', 'type': 'datetime-local'}),
        }


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('owner',)

newsletter/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from newsletter.forms import ClientForm, MessageForm, MailForm
from newsletter.models import Client, Message, Mail
from newsletter.services import get_cache_for_mailings


class IndexView(TemplateView):
    template_name = 'newsletter/index.html'
    extra_context = {
        'title': 'Главная',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mail_count'] = get_cache_for_mailings()
        context_data['active_mail_count'] = len(Mail.objects.filter(is_active=True))
        context_data['client_count'] = len(Client.objects.all())
        context_data['object_list'] = random.sample(list(Blog.objects.all()), 3)

        return context_data


def contacts(request):
    context = {
        'title': "Контакты",
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f"{name} ({phone}, {email}): {message}")

    return render(request, 'newsletter/contacts.html', context)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': "Клиенты сервиса ",
    }

    def get_queryset(self, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return Client.objects.all()
        return Client.objects.filter(owner=self.request.user)


class ClientDetailView(DetailView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('newsletter:client_list')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('newsletter:client_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'title': "Сообщения для рассылки ",
    }

    def get_queryset(self, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return Message.objects.all()
        return Message.objects.filter(owner=self.request.user)


class MessageDetailView(DetailView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('newsletter:message_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('newsletter:message_list')


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('newsletter:message_list')


class MailListView(LoginRequiredMixin, ListView):
    model = Mail
    extra_context = {
        'title': "Рассылки ",
    }

    def get_queryset(self, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return Mail.objects.all()
        p_view_mail = Permission.objects.get(codename='view_mail')
        p_change_mail = Permission.objects.get(codename='change_mail')
        p_delete_mail = Permission.objects.get(codename='delete_mail')
        self.request.user.user_permissions.set([p_view_mail, p_change_mail, p_delete_mail])
        return Mail.objects.filter(owner=self.request.user)


class MailDetailView(PermissionRequiredMixin, DetailView):
    model = Mail
    permission_required = 'newsletter.view_mail'


class MailCreateView(CreateView):
    model = Mail
    form_class = MailForm
    success_url = reverse_lazy('newsletter:mail_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailUpdateView(PermissionRequiredMixin, UpdateView):
    model = Mail
    form_class = MailForm
    success_url = reverse_lazy('newsletter:mail_list')
    permission_required = 'newsletter.change_mail'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class MailDeleteView(PermissionRequiredMixin, DeleteView):
    model = Mail
    success_url = reverse_lazy('newsletter:mail_list')
    permission_required = 'newsletter.delete_mail'


def toogle_activity(request, pk):
    mail_item = get_object_or_404(Mail, pk=pk)
    if mail_item.is_active:
        mail_item.is_active = False
    else:
        mail_item.is_active = True
    mail_item.save()
    return redirect('newsletter:mail_list')

newsletter/templates/newsletter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{title}}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/justified-nav.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="masthead">
        <h3 class="text-muted">NewsLetter/Сервис рассылок</h3>
        {% include 'newsletter/includes/inc_menu.html' with object=object %}
    </div>
    <div class="jumbotron">
        <h1>{{title}}</h1>
    </div>
    {% block content %}
    {% endblock %}
    <footer class="footer">
        <p>&copy; 2024-{% now 'Y'%}</p>
    </footer>
</div>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

newsletter/templates/newsletter/client_confirm_delete.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить Клиента Сервиса "{{object}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'newsletter:client_list' %}" type="submit" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/client_detail.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <h5 class="card-header"> Клиент </h5>
                <div class="card-body">
                    <p class="card-text">email: {{object.email}} </p>
                    <p class="card-text">Фамилия: {{object.last_name}} </p>
                    <p class="card-text">Имя: {{object.first_name}} </p>
                    <p class="card-text">Отчество: {{object.father_name}} </p>
                    <p class="card-text">Комментарий: {{object.comment}} </p>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/client_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/client_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    {% if not user.is_staff%}
    <p><a class="btn btn-primary" href="{% url 'newsletter:create_client'%}" role="button">Добавить клиента</a></p>
    {% endif %}
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Отчество</th>
        <th scope="col">Email</th>
        <th scope="col">Комментарий</th>
        {% if user.is_staff or user.is_superuser%}
        <th scope="col">Автор</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <td>{{object.last_name}}</td>
        <td>{{object.first_name}}</td>
        <td>{{object.father_name}}</td>
        <td>{{object.email}}</td>
        <td>{{object.comment}}</td>
        {% if user.is_staff or user.is_superuser%}
        <td>{{object.owner}}</td>
        {% endif %}
        <td><a href="{% url 'newsletter:view_client' object.pk%}" class="btn btn-primary">detail view</a></td>
        {% if not user.is_staff%}
        <td><a href="{% url 'newsletter:edit_client' object.pk%}" class="btn btn-primary">edit</a></td>
        <td><a href="{% url 'newsletter:delete_client' object.pk%}" class="btn btn-primary">delete</a></td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

newsletter/templates/newsletter/contacts.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="email">email</label>
                            <input type="email" name="email" class="form-control" id="email"
                                   placeholder="Контактный email" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Ваше сообщение"
                                      required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mail_confirm_delete.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить Рассылку "{{object}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'newsletter:client_list' %}" type="submit" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mail_detail.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <h5 class="card-header"> Название рассылки: {{object.name}} </h5>
                <div class="card-body">
                    <p class="card-text">Кому (клиенты сервиса):</p>
                    <ul>
                        {% for value in object.clients.all.values_list %}
                        <li>{{value.1 }}</li>
                        {% endfor%}
                    </ul>
                    <p class="card-text">Сообщение: {{object.message}} </p>
                    <p class="card-text">Дата начала рассылки: {{object.date_start}} </p>
                    <p class="card-text">Дата окончания рассылки: {{object.date_end}} </p>
                    <p class="card-text">Время рассылки: {{object.start_time}} </p>
                    <p class="card-text">Периодичность рассылки: {{object.period}} </p>
                    <p class="card-text">Статус рассылки: {{object.status}} </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mail_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mail_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    {% if not user.is_staff%}
    <p><a class="btn btn-primary" href="{% url 'newsletter:create_mail'%}" role="button">Добавить рассылку</a></p>
    {% endif %}
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Название рассылки</th>
        <th scope="col">Кому (клиенты сервиса)</th>
        <th scope="col">Сообщение для рассылки</th>
        <th scope="col">Статус рассылки</th>
        {% if user.is_staff or user.is_superuser%}
        <th scope="col">Автор</th>
        <th scope="col">Активация рассылки</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <td>{{object.name|slice:50}}</td>
        <td>
            <ul>
                {% for value in object.clients.all.values_list %}
                <li>{{value.1 }}</li>
                {% endfor%}
            </ul>
        </td>
        <td>{{object.message|slice:50}}</td>
        <td>{{object.status|slice:50}}</td>
        {% if user.is_staff or user.is_superuser%}
        <td>{{object.owner}}</td>
        <td>{{object.is_active}}</td>
        {% endif %}
        {% if perms.mails.set_is_active %}
        {% if object.is_active %}
        <td><a href="{% url 'newsletter:toogle_activity' object.pk %}" class="btn btn-warning">Деактивировать</a></td>
        {% else %}
        <td><a href="{% url 'newsletter:toogle_activity' object.pk %}" class="btn btn-success">Активировать</a></td>
        {% endif %}
        {% endif %}
        <td><a href="{% url 'newsletter:view_mail' object.pk%}" class="btn btn-primary">detail view</a></td>
        {% if not perms.mails.set_is_active %}
        <td><a href="{% url 'newsletter:edit_mail' object.pk%}" class="btn btn-primary">edit</a></td>
        <td><a href="{% url 'newsletter:delete_mail' object.pk%}" class="btn btn-primary">delete</a></td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

newsletter/templates/newsletter/message_confirm_delete.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить Сообщение для рассылки "{{object}} {{object.body|slice:50}}..."?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'newsletter:client_list' %}" type="submit" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_detail.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">

                <h5 class="card-header"> Тема письма: {{object}} </h5>
                <div class="card-body">
                    <h5 class="card-title">Тело письма: </h5>
                    <p class="card-text"> {{object.body}} </p>
                </div>
            </div>
        </div>
    </div>
</div>
    {% endblock %}

newsletter/templates/newsletter/message_form.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif%}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/message_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    {% if not user.is_staff%}
    <p><a class="btn btn-primary" href="{% url 'newsletter:create_message'%}" role="button">Добавить сообщение для
        рассылки</a></p>
    {% endif %}
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Тема письма</th>
        <th scope="col">Тело письма</th>
        {% if user.is_staff or user.is_superuser%}
        <th scope="col">Автор</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <td>{{object|slice:50}}</td>
        <td>{{object.body|slice:50}}</td>
        {% if user.is_staff or user.is_superuser%}
        <td>{{object.owner}}</td>
        {% endif %}
        <td><a href="{% url 'newsletter:view_message' object.pk%}" class="btn btn-primary">detail view</a></td>
        {% if not user.is_staff%}
        <td><a href="{% url 'newsletter:edit_message' object.pk%}" class="btn btn-primary">edit</a></td>
        <td><a href="{% url 'newsletter:delete_message' object.pk%}" class="btn btn-primary">delete</a></td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}