blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import blog, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', blog, name='list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('newsletter.urls', namespace='newsletter')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blogs/', **NULLABLE, verbose_name='изображение')
    date_is_published = models.DateField(**NULLABLE, verbose_name='дата публикации')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView

from blog.models import Blog


def blog(request):
    context = {
        'object_list': Blog.objects.all(),
        'title': " Блог",
    }
    return render(request, 'blog/blog_list.html', context)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_detail.html
{% extends 'newsletter/base.html' %}
{% load static %}
{% block content%}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {{object.title }}
                    </h3>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <p> {{object.body}}</p>
                        <p> Дата публикации: {{object.date_is_published}}</p>
                        <img class="card-img-top"
                             src="/media/{{object.preview}}"
                             alt="Card image cap">
                    </ul>
                </div>
            </div>
            <div class="card-footer"></div>
            Просмотры: {{ object.views_count }}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'newsletter/base.html' %}
{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-lg-4">
        <h2> {{object|title}}</h2>
        <p> {{object.body|slice:300}}</p>
        <p><a class="btn btn-primary" href="{% url 'blog:view' object.pk %}" role="button">Подробнее &raquo;</a></p>
    </div>
    {% endfor %}
</div>
{% endblock %}